
package com.mrted.ws;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "FoAdvertWebService", targetNamespace = "http://ws.mrted.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface FoAdvertWebService {


    /**
     * 
     * @param langCode
     * @param postingTargetId
     * @param showImages
     * @return
     *     returns com.mrted.ws.AdvertisementDto
     */
    @WebMethod
    @WebResult(name = "advertisement", targetNamespace = "http://ws.mrted.com/")
    @RequestWrapper(localName = "getAdvertisementById", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.GetAdvertisementById")
    @ResponseWrapper(localName = "getAdvertisementByIdResponse", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.GetAdvertisementByIdResponse")
    public AdvertisementDto getAdvertisementById(
        @WebParam(name = "postingTargetId", targetNamespace = "http://ws.mrted.com/")
        Long postingTargetId,
        @WebParam(name = "langCode", targetNamespace = "http://ws.mrted.com/")
        LangCode langCode,
        @WebParam(name = "showImages", targetNamespace = "http://ws.mrted.com/")
        Boolean showImages);

    /**
     * 
     * @param postingTargetId
     * @param tokenString
     * @return
     *     returns java.util.List<com.mrted.ws.AssignedImageDto>
     */
    @WebMethod
    @WebResult(name = "advertisementImage", targetNamespace = "http://ws.mrted.com/")
    @RequestWrapper(localName = "getAdvertisementImages", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.GetAdvertisementImages")
    @ResponseWrapper(localName = "getAdvertisementImagesResponse", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.GetAdvertisementImagesResponse")
    public List<AssignedImageDto> getAdvertisementImages(
        @WebParam(name = "postingTargetId", targetNamespace = "http://ws.mrted.com/")
        Long postingTargetId,
        @WebParam(name = "tokenString", targetNamespace = "http://ws.mrted.com/")
        String tokenString);

    /**
     * 
     * @param langCode
     * @param tokenString
     * @return
     *     returns com.mrted.ws.AdvertisementDto
     */
    @WebMethod
    @WebResult(name = "advertisement", targetNamespace = "http://ws.mrted.com/")
    @RequestWrapper(localName = "getAdvertisementPreviewByToken", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.GetAdvertisementPreviewByToken")
    @ResponseWrapper(localName = "getAdvertisementPreviewByTokenResponse", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.GetAdvertisementPreviewByTokenResponse")
    public AdvertisementDto getAdvertisementPreviewByToken(
        @WebParam(name = "tokenString", targetNamespace = "http://ws.mrted.com/")
        String tokenString,
        @WebParam(name = "langCode", targetNamespace = "http://ws.mrted.com/")
        LangCode langCode);

    /**
     * 
     * @param langCode
     * @param searchCriteriaDto
     * @param firstResult
     * @param maxResults
     * @param sortingDetailsDto
     * @return
     *     returns com.mrted.ws.AdvertisementResultDto
     */
    @WebMethod
    @WebResult(name = "advertisementResult", targetNamespace = "http://ws.mrted.com/")
    @RequestWrapper(localName = "getAdvertisements", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.GetAdvertisements")
    @ResponseWrapper(localName = "getAdvertisementsResponse", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.GetAdvertisementsResponse")
    public AdvertisementResultDto getAdvertisements(
        @WebParam(name = "firstResult", targetNamespace = "http://ws.mrted.com/")
        int firstResult,
        @WebParam(name = "maxResults", targetNamespace = "http://ws.mrted.com/")
        int maxResults,
        @WebParam(name = "searchCriteriaDto", targetNamespace = "http://ws.mrted.com/")
        SearchCriteriaDto searchCriteriaDto,
        @WebParam(name = "sortingDetailsDto", targetNamespace = "http://ws.mrted.com/")
        SortingDetailsDto sortingDetailsDto,
        @WebParam(name = "langCode", targetNamespace = "http://ws.mrted.com/")
        LangCode langCode);

    /**
     * 
     * @param langCode
     * @param searchCriteriaDto
     * @param pageNumber
     * @param sortingDetailsDto
     * @return
     *     returns com.mrted.ws.AdvertisementResultDto
     */
    @WebMethod
    @WebResult(name = "advertisementResult", targetNamespace = "http://ws.mrted.com/")
    @RequestWrapper(localName = "getAdvertisementsByPage", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.GetAdvertisementsByPage")
    @ResponseWrapper(localName = "getAdvertisementsByPageResponse", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.GetAdvertisementsByPageResponse")
    public AdvertisementResultDto getAdvertisementsByPage(
        @WebParam(name = "pageNumber", targetNamespace = "http://ws.mrted.com/")
        int pageNumber,
        @WebParam(name = "searchCriteriaDto", targetNamespace = "http://ws.mrted.com/")
        SearchCriteriaDto searchCriteriaDto,
        @WebParam(name = "sortingDetailsDto", targetNamespace = "http://ws.mrted.com/")
        SortingDetailsDto sortingDetailsDto,
        @WebParam(name = "langCode", targetNamespace = "http://ws.mrted.com/")
        LangCode langCode);

    /**
     * 
     * @return
     *     returns com.mrted.ws.AdvertisementSortingColumns
     */
    @WebMethod
    @WebResult(name = "advertisementSortingColumns", targetNamespace = "http://ws.mrted.com/")
    @RequestWrapper(localName = "getAdvertisementsSortingColumns", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.GetAdvertisementsSortingColumns")
    @ResponseWrapper(localName = "getAdvertisementsSortingColumnsResponse", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.GetAdvertisementsSortingColumnsResponse")
    public AdvertisementSortingColumns getAdvertisementsSortingColumns();

    /**
     * 
     * @param postingTargetId
     * @return
     *     returns java.util.List<com.mrted.ws.AttachmentContentDto>
     */
    @WebMethod
    @WebResult(name = "attachment", targetNamespace = "http://ws.mrted.com/")
    @RequestWrapper(localName = "getAttachments", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.GetAttachments")
    @ResponseWrapper(localName = "getAttachmentsResponse", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.GetAttachmentsResponse")
    public List<AttachmentContentDto> getAttachments(
        @WebParam(name = "postingTargetId", targetNamespace = "http://ws.mrted.com/")
        Long postingTargetId);

    /**
     * 
     * @param tokenString
     * @return
     *     returns java.util.List<com.mrted.ws.AttachmentContentDto>
     */
    @WebMethod
    @WebResult(name = "attachment", targetNamespace = "http://ws.mrted.com/")
    @RequestWrapper(localName = "getAttachmentsFromToken", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.GetAttachmentsFromToken")
    @ResponseWrapper(localName = "getAttachmentsFromTokenResponse", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.GetAttachmentsFromTokenResponse")
    public List<AttachmentContentDto> getAttachmentsFromToken(
        @WebParam(name = "tokenString", targetNamespace = "http://ws.mrted.com/")
        String tokenString);

    /**
     * 
     * @param searchCriteriaSorting
     * @param langCode
     * @param lovOrders
     * @return
     *     returns com.mrted.ws.AvailableSearchCriteriaDto
     */
    @WebMethod
    @WebResult(name = "standardCriteriaWithLovs", targetNamespace = "http://ws.mrted.com/")
    @RequestWrapper(localName = "getCriteria", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.GetCriteria")
    @ResponseWrapper(localName = "getCriteriaResponse", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.GetCriteriaResponse")
    public AvailableSearchCriteriaDto getCriteria(
        @WebParam(name = "langCode", targetNamespace = "http://ws.mrted.com/")
        LangCode langCode,
        @WebParam(name = "searchCriteriaSorting", targetNamespace = "http://ws.mrted.com/")
        SearchCriteriaSorting searchCriteriaSorting,
        @WebParam(name = "lovOrders", targetNamespace = "http://ws.mrted.com/")
        String lovOrders);

    /**
     * 
     * @param langCode
     * @param searchCriteriaDto
     * @param firstResult
     * @param maxResults
     * @param sortingDetailsDto
     * @return
     *     returns com.mrted.ws.SimpleAdvertisementResultDto
     */
    @WebMethod
    @WebResult(name = "simpleAdvertisementResult", targetNamespace = "http://ws.mrted.com/")
    @RequestWrapper(localName = "getSimpleAdvertisements", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.GetSimpleAdvertisements")
    @ResponseWrapper(localName = "getSimpleAdvertisementsResponse", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.GetSimpleAdvertisementsResponse")
    public SimpleAdvertisementResultDto getSimpleAdvertisements(
        @WebParam(name = "firstResult", targetNamespace = "http://ws.mrted.com/")
        int firstResult,
        @WebParam(name = "maxResults", targetNamespace = "http://ws.mrted.com/")
        int maxResults,
        @WebParam(name = "searchCriteriaDto", targetNamespace = "http://ws.mrted.com/")
        SearchCriteriaDto searchCriteriaDto,
        @WebParam(name = "sortingDetailsDto", targetNamespace = "http://ws.mrted.com/")
        SortingDetailsDto sortingDetailsDto,
        @WebParam(name = "langCode", targetNamespace = "http://ws.mrted.com/")
        LangCode langCode);

    /**
     * 
     * @param langCode
     * @param searchCriteriaDto
     * @param pageNumber
     * @param sortingDetailsDto
     * @return
     *     returns com.mrted.ws.SimpleAdvertisementResultDto
     */
    @WebMethod
    @WebResult(name = "simpleAdvertisementResult", targetNamespace = "http://ws.mrted.com/")
    @RequestWrapper(localName = "getSimpleAdvertisementsByPage", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.GetSimpleAdvertisementsByPage")
    @ResponseWrapper(localName = "getSimpleAdvertisementsByPageResponse", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.GetSimpleAdvertisementsByPageResponse")
    public SimpleAdvertisementResultDto getSimpleAdvertisementsByPage(
        @WebParam(name = "pageNumber", targetNamespace = "http://ws.mrted.com/")
        int pageNumber,
        @WebParam(name = "searchCriteriaDto", targetNamespace = "http://ws.mrted.com/")
        SearchCriteriaDto searchCriteriaDto,
        @WebParam(name = "sortingDetailsDto", targetNamespace = "http://ws.mrted.com/")
        SortingDetailsDto sortingDetailsDto,
        @WebParam(name = "langCode", targetNamespace = "http://ws.mrted.com/")
        LangCode langCode);

    /**
     * 
     * @param searchCriteriaSorting
     * @param langCode
     * @return
     *     returns com.mrted.ws.AvailableSearchCriteriaDto
     */
    @WebMethod
    @WebResult(name = "standardCriteria", targetNamespace = "http://ws.mrted.com/")
    @RequestWrapper(localName = "getStandardCriteria", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.GetStandardCriteria")
    @ResponseWrapper(localName = "getStandardCriteriaResponse", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.GetStandardCriteriaResponse")
    public AvailableSearchCriteriaDto getStandardCriteria(
        @WebParam(name = "langCode", targetNamespace = "http://ws.mrted.com/")
        LangCode langCode,
        @WebParam(name = "searchCriteriaSorting", targetNamespace = "http://ws.mrted.com/")
        SearchCriteriaSorting searchCriteriaSorting);

}
