
package com.mrted.ws;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "LovWebService", targetNamespace = "http://ws.mrted.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface LovWebService {


    /**
     * 
     * @param lovTypeCategory
     * @return
     *     returns java.util.List<com.mrted.ws.LovDto>
     */
    @WebMethod
    @WebResult(name = "lovNames", targetNamespace = "http://ws.mrted.com/")
    @RequestWrapper(localName = "getLovNames", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.GetLovNames")
    @ResponseWrapper(localName = "getLovNamesResponse", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.GetLovNamesResponse")
    public List<LovDto> getLovNames(
        @WebParam(name = "lovTypeCategory", targetNamespace = "")
        LovTypeCategory lovTypeCategory);

    /**
     * 
     * @param langCode
     * @param lovName
     * @return
     *     returns java.util.List<com.mrted.ws.LovDescendantDto>
     */
    @WebMethod
    @WebResult(name = "lovWithValues", targetNamespace = "http://ws.mrted.com/")
    @RequestWrapper(localName = "getLovWithValuesByName", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.GetLovWithValuesByName")
    @ResponseWrapper(localName = "getLovWithValuesByNameResponse", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.GetLovWithValuesByNameResponse")
    public List<LovDescendantDto> getLovWithValuesByName(
        @WebParam(name = "lovName", targetNamespace = "http://ws.mrted.com/")
        String lovName,
        @WebParam(name = "langCode", targetNamespace = "http://ws.mrted.com/")
        LangCode langCode);

    /**
     * 
     * @param langCode
     * @param lovNames
     * @return
     *     returns java.util.List<com.mrted.ws.LovDto>
     */
    @WebMethod
    @WebResult(name = "lovWithValues", targetNamespace = "http://ws.mrted.com/")
    @RequestWrapper(localName = "getLovsWithValues", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.GetLovsWithValues")
    @ResponseWrapper(localName = "getLovsWithValuesResponse", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.GetLovsWithValuesResponse")
    public List<LovDto> getLovsWithValues(
        @WebParam(name = "lovNames", targetNamespace = "http://ws.mrted.com/")
        List<String> lovNames,
        @WebParam(name = "langCode", targetNamespace = "http://ws.mrted.com/")
        LangCode langCode);

}
