
package com.mrted.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "LovWebService", targetNamespace = "http://ws.mrted.com/", wsdlLocation = "file:/B:/Projets/ucanss/lsr-components/src/main/resources/wsdl/LOV.xml")
public class LovWebService_Service
    extends Service
{

    private final static URL LOVWEBSERVICE_WSDL_LOCATION;
    private final static WebServiceException LOVWEBSERVICE_EXCEPTION;
    private final static QName LOVWEBSERVICE_QNAME = new QName("http://ws.mrted.com/", "LovWebService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/B:/Projets/ucanss/lsr-components/src/main/resources/wsdl/LOV.xml");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        LOVWEBSERVICE_WSDL_LOCATION = url;
        LOVWEBSERVICE_EXCEPTION = e;
    }

    public LovWebService_Service() {
        super(__getWsdlLocation(), LOVWEBSERVICE_QNAME);
    }

    public LovWebService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), LOVWEBSERVICE_QNAME, features);
    }

    public LovWebService_Service(URL wsdlLocation) {
        super(wsdlLocation, LOVWEBSERVICE_QNAME);
    }

    public LovWebService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, LOVWEBSERVICE_QNAME, features);
    }

    public LovWebService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public LovWebService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns LovWebService
     */
    @WebEndpoint(name = "LovWebServicePort")
    public LovWebService getLovWebServicePort() {
        return super.getPort(new QName("http://ws.mrted.com/", "LovWebServicePort"), LovWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LovWebService
     */
    @WebEndpoint(name = "LovWebServicePort")
    public LovWebService getLovWebServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.mrted.com/", "LovWebServicePort"), LovWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (LOVWEBSERVICE_EXCEPTION!= null) {
            throw LOVWEBSERVICE_EXCEPTION;
        }
        return LOVWEBSERVICE_WSDL_LOCATION;
    }

}
