
package com.mrted.ws;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SearchAgentWebService", targetNamespace = "http://ws.mrted.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SearchAgentWebService {


    /**
     * 
     * @param searchAgentDto
     * @param sendEmail
     * @param language
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "create", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.Create")
    @ResponseWrapper(localName = "createResponse", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.CreateResponse")
    public String create(
        @WebParam(name = "searchAgentDto", targetNamespace = "http://ws.mrted.com/")
        SearchAgentDto searchAgentDto,
        @WebParam(name = "sendEmail", targetNamespace = "http://ws.mrted.com/")
        boolean sendEmail,
        @WebParam(name = "language", targetNamespace = "http://ws.mrted.com/")
        LangCode language);

    /**
     * 
     * @param token
     */
    @WebMethod
    @RequestWrapper(localName = "delete", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.Delete")
    @ResponseWrapper(localName = "deleteResponse", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.DeleteResponse")
    public void delete(
        @WebParam(name = "token", targetNamespace = "http://ws.mrted.com/")
        String token);

    /**
     * 
     * @param token
     * @return
     *     returns java.util.List<com.mrted.ws.SearchAgentDetails>
     */
    @WebMethod
    @WebResult(name = "searchAgentDetails", targetNamespace = "http://ws.mrted.com/")
    @RequestWrapper(localName = "getActiveSearchAgents", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.GetActiveSearchAgents")
    @ResponseWrapper(localName = "getActiveSearchAgentsResponse", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.GetActiveSearchAgentsResponse")
    public List<SearchAgentDetails> getActiveSearchAgents(
        @WebParam(name = "token", targetNamespace = "http://ws.mrted.com/")
        String token);

    /**
     * 
     * @param token
     * @param searchAgentDto
     * @param language
     */
    @WebMethod
    @RequestWrapper(localName = "update", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.Update")
    @ResponseWrapper(localName = "updateResponse", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.UpdateResponse")
    public void update(
        @WebParam(name = "searchAgentDto", targetNamespace = "http://ws.mrted.com/")
        SearchAgentDto searchAgentDto,
        @WebParam(name = "token", targetNamespace = "http://ws.mrted.com/")
        String token,
        @WebParam(name = "language", targetNamespace = "http://ws.mrted.com/")
        LangCode language);

}
