
package com.mrted.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SearchAgentWebService", targetNamespace = "http://ws.mrted.com/", wsdlLocation = "file:/B:/Projets/ucanss/lsr-components/src/main/resources/wsdl/SearchAgent.xml")
public class SearchAgentWebService_Service
    extends Service
{

    private final static URL SEARCHAGENTWEBSERVICE_WSDL_LOCATION;
    private final static WebServiceException SEARCHAGENTWEBSERVICE_EXCEPTION;
    private final static QName SEARCHAGENTWEBSERVICE_QNAME = new QName("http://ws.mrted.com/", "SearchAgentWebService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/B:/Projets/ucanss/lsr-components/src/main/resources/wsdl/SearchAgent.xml");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SEARCHAGENTWEBSERVICE_WSDL_LOCATION = url;
        SEARCHAGENTWEBSERVICE_EXCEPTION = e;
    }

    public SearchAgentWebService_Service() {
        super(__getWsdlLocation(), SEARCHAGENTWEBSERVICE_QNAME);
    }

    public SearchAgentWebService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), SEARCHAGENTWEBSERVICE_QNAME, features);
    }

    public SearchAgentWebService_Service(URL wsdlLocation) {
        super(wsdlLocation, SEARCHAGENTWEBSERVICE_QNAME);
    }

    public SearchAgentWebService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SEARCHAGENTWEBSERVICE_QNAME, features);
    }

    public SearchAgentWebService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SearchAgentWebService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SearchAgentWebService
     */
    @WebEndpoint(name = "SearchAgentWebServicePort")
    public SearchAgentWebService getSearchAgentWebServicePort() {
        return super.getPort(new QName("http://ws.mrted.com/", "SearchAgentWebServicePort"), SearchAgentWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SearchAgentWebService
     */
    @WebEndpoint(name = "SearchAgentWebServicePort")
    public SearchAgentWebService getSearchAgentWebServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.mrted.com/", "SearchAgentWebServicePort"), SearchAgentWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SEARCHAGENTWEBSERVICE_EXCEPTION!= null) {
            throw SEARCHAGENTWEBSERVICE_EXCEPTION;
        }
        return SEARCHAGENTWEBSERVICE_WSDL_LOCATION;
    }

}
